// Generated by Wrangler on Mon Aug 05 2024 09:36:01 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	cache: KVNamespace;
	SERVICE_ACCOUNT: string;
	DB: D1Database;
}
