#:schema node_modules/wrangler/config-schema.json
name = "rog-backend"
main = "src/index.ts"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "rog"
database_id = "0d395f94-86cf-468d-b9de-050e8266255e"